version: '3'

services:
  # Define o serviço da aplicação
  app:
    build: . 
    command: /bin/sh -c "npm install && npm start"
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/app
    depends_on:
      - db

  # Define o serviço do banco de dados
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eztudy
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: "UTC"  # Ajusta o timezone se necessário
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"  # Corrigido para a porta padrão do MySQL
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

# Define um volume nomeado para persistência dos dados do banco de dados
volumes:
  db_data:
